# Generated by Django 5.1.1 on 2024-10-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
